# Generated by Django 3.0.5 on 2020-06-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foundation',
            old_name='cover',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='foundation',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
