# Generated by Django 3.0.5 on 2020-06-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0002_auto_20200623_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundation',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
