# Generated by Django 3.0.5 on 2020-12-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0004_foundation_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foundation',
            name='cropping',
        ),
    ]
